# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(['testLib'])
scripts.BasicSConscript.tests(noBuildList=['testLib.cc'],
                              ignoreList=['testLib.py'])
