# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils")
env.LoadableModuleIncomplete("_policyLib", Split("policyLib.i"), LIBS=env.libs["boost"] + ["utils", "daf_base", "pex_exceptions", "pex_policy", "jaula"])

