# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_exceptions")
env.LoadableModuleIncomplete("_policyLib", Split("policyLib.i"), LIBS=env.libs["pex_policy"])
