# -*- python -*-
Import('env')
import os

env.SharedLibrary('pex_policy', map(lambda str: "../src/" + str,
                            ["Policy.cc",
                             "PolicySource.cc",
                             "PolicyFile.cc",
                             "PolicyString.cc",
                             "PolicyDestination.cc",
                             "PolicyStreamDestination.cc",
                             "PolicyStringDestination.cc",
                             "PolicyParser.cc",
                             "PolicyParserFactory.cc",
                             "SupportedFormats.cc",
                             "Dictionary.cc",
                             "PolicyConfigured.cc",
                             "DefaultPolicyFile.cc",
                             "exceptions.cc",
                             "parserexceptions.cc",
                             "PolicyWriter.cc",
                             "paf/PAFWriter.cc",
                             "paf/PAFParser.cc",
                             "paf/PAFParserFactory.cc"
                            ]),
                  LIBS=filter(lambda x : x != "pex_policy", env.libs["pex_policy"]))
