# -*- python -*-
Import('env')
import os

env.SharedLibrary('pex_policy', map(lambda str: "../src/" + str,
                            ["Policy.cc",
                             "PolicySource.cc",
                             "PolicyFile.cc",
                             "PolicyParser.cc",
                             "PolicyParserFactory.cc",
                             "SupportedFormats.cc",
                             "Dictionary.cc",
                             "json/JSONParser.cc",
                             "json/JSONParserFactory.cc",
                             "paf/PAFParser.cc",
                             "paf/PAFParserFactory.cc"
                            ]),
                  LIBS=env.getlibs("boost jaula"))

