# -*- python -*-
Import('env')
import os

env.SharedLibrary('pex_policy', map(lambda str: "../src/" + str,
                            ["Policy.cc",
                             "PolicySource.cc",
                             "PolicyFile.cc",
                             "PolicyParser.cc",
                             "PolicyParserFactory.cc",
                             "SupportedFormats.cc",
                             "Dictionary.cc",
                             "paf/PAFParser.cc",
                             "paf/PAFParserFactory.cc"
                            ]),
                  LIBS=filter(lambda x : x != "pex_policy", env.libs["pex_policy"]))
